syntax = "proto3";

package  github.com.PechatnovVladimir.msa_big_tech.social.api;

option go_package = "github.com/PechatnovVladimir/msa_big_tech/social/pkg;social";

service SocialService {
  rpc SendFriendRequest (SendFriendRequestRequest) returns (SendFriendRequestResponse) {}

  rpc ListRequests (ListRequestsRequest) returns (ListRequestsResponse) {}

  rpc AcceptFriendRequest (AcceptFriendRequestRequest) returns (AcceptFriendRequestResponse) {}

  rpc DeclineFriendRequest (DeclineFriendRequestRequest) returns (DeclineFriendRequestResponse) {}

  rpc RemoveFriend (RemoveFriendRequest) returns (RemoveFriendResponse) {}

  rpc ListFriends (ListFriendsRequest) returns (ListFriendsResponse){}
}
enum Status {
  UNKNOWN = 0;
  PENDING = 1;
  ACCEPTED = 2;
  DECLINED  = 3;
}

message FriendRequest {
  int64 request_id = 1;
  Status status = 2;
}

message SendFriendRequestRequest {
  int64 user_id = 1;
}

message SendFriendRequestResponse {
  FriendRequest FriendRequest = 1;
}

message ListRequestsRequest {
  int64 user_id = 1;
}

message ListRequestsResponse {
  repeated FriendRequest FriendRequest = 1;
}

message AcceptFriendRequestRequest {
  int64 request_id = 1;
}

message AcceptFriendRequestResponse {
  FriendRequest FriendRequest = 1;
}

message DeclineFriendRequestRequest {
  int64 request_id = 1;
}

message DeclineFriendRequestResponse {
  FriendRequest FriendRequest = 1;
}

message RemoveFriendRequest {
  int64 user_id =1;
}

message RemoveFriendResponse {

}

message ListFriendsRequest {
  int64 user_id = 1;
  int64 limit = 2;
  optional string cursor = 3;
}

message ListFriendsResponse {
  repeated int64 friend_user_ids = 1;
  optional string next_cursor = 2;
}