syntax = "proto3";

package  github.com.PechatnovVladimir.msa_big_tech.social.api;

option go_package = "github.com/PechatnovVladimir/msa_big_tech/social/pkg;social";

import "google/protobuf/timestamp.proto";

import "google/api/annotations.proto";

service SocialService {
  rpc SendFriendRequest (SendFriendRequestRequest) returns (SendFriendRequestResponse) {
    option (google.api.http) = {
      post: "/social/v1/SendFriendRequest"
      body: "*"
    };

  }

  rpc ListRequests (ListRequestsRequest) returns (ListRequestsResponse) {
    option (google.api.http) = {
      get: "/social/v1/ListRequests/{user_id}"
    };
  }

  rpc AcceptFriendRequest (AcceptFriendRequestRequest) returns (AcceptFriendRequestResponse) {
    option (google.api.http) = {
      post: "/social/v1/AcceptFriendRequest"
      body: "*"
    };
  }

  rpc DeclineFriendRequest (DeclineFriendRequestRequest) returns (DeclineFriendRequestResponse) {
    option (google.api.http) = {
      post: "/social/v1/DeclineFriendRequest"
      body: "*"
    };
  }

  rpc RemoveFriend (RemoveFriendRequest) returns (RemoveFriendResponse) {
    option (google.api.http) = {
      delete: "/social/v1/RemoveFriend/{user_id}"
    };
  }

  rpc ListFriends (ListFriendsRequest) returns (ListFriendsResponse){
    option (google.api.http) = {
      get: "/social/v1/ListFriends/{user_id}"
    };
  }
}
enum Status {
  UNKNOWN = 0;
  PENDING = 1;
  ACCEPTED = 2;
  DECLINED  = 3;
}

message FriendRequest {
  int64 request_id = 1;
  Status status = 2;
}

message SendFriendRequestRequest {
  int64 user_id = 1;
}

message SendFriendRequestResponse {
  FriendRequest FriendRequest = 1;
}

message ListRequestsRequest {
  int64 user_id = 1;
}

message ListRequestsResponse {
  repeated FriendRequest FriendRequest = 1;
}

message AcceptFriendRequestRequest {
  int64 request_id = 1;
}

message AcceptFriendRequestResponse {
  FriendRequest FriendRequest = 1;
}

message DeclineFriendRequestRequest {
  int64 request_id = 1;
}

message DeclineFriendRequestResponse {
  FriendRequest FriendRequest = 1;
}

message RemoveFriendRequest {
  int64 user_id =1;
}

message RemoveFriendResponse {

}

message Cursor {
  int64 user_id = 1;
  google.protobuf.Timestamp created_at = 2;
}


message ListFriendsRequest {
  int64 user_id = 1;
  int64 limit = 2;
  optional Cursor cursor = 3;
}

message ListFriendsResponse {
  repeated int64 friend_user_ids = 1;
  optional Cursor next_cursor = 2;
}