// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/social/v1/service.proto

package social

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_social_v1_service_proto protoreflect.FileDescriptor

const file_api_social_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/social/v1/service.proto\x127github.com.PechatnovVladimir.msa_big_tech.social.api.v1\x1a\x1capi/social/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xdc\n" +
	"\n" +
	"\rSocialService\x12\xe3\x01\n" +
	"\x11SendFriendRequest\x12Q.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SendFriendRequestRequest\x1aR.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SendFriendRequestResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/social/SendFriendRequest\x12\xd6\x01\n" +
	"\fListRequests\x12L.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListRequestsRequest\x1aM.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListRequestsResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/social/ListRequests/{user_id}\x12\xeb\x01\n" +
	"\x13AcceptFriendRequest\x12S.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.AcceptFriendRequestRequest\x1aT.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.AcceptFriendRequestResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/social/AcceptFriendRequest\x12\xef\x01\n" +
	"\x14DeclineFriendRequest\x12T.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.DeclineFriendRequestRequest\x1aU.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.DeclineFriendRequestResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/social/DeclineFriendRequest\x12\xd6\x01\n" +
	"\fRemoveFriend\x12L.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.RemoveFriendRequest\x1aM.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.RemoveFriendResponse\")\x82\xd3\xe4\x93\x02#*!/v1/social/RemoveFriend/{user_id}\x12\xd2\x01\n" +
	"\vListFriends\x12K.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListFriendsRequest\x1aL.github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListFriendsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/social/ListFriends/{user_id}B\xc0\x03\x92A*\x12%\n" +
	"\n" +
	"Social API\x12\x12API social-service2\x031.0*\x01\x01\n" +
	";com.github.com.PechatnovVladimir.msa_big_tech.social.api.v1B\fServiceProtoP\x01ZIgithub.com/PechatnovVladimir/msa_big_tech/social/pkg/api/social/v1;social\xa2\x02\x06GCPMSA\xaa\x025Github.Com.PechatnovVladimir.MsaBigTech.Social.Api.V1\xca\x025Github\\Com\\PechatnovVladimir\\MsaBigTech\\Social\\Api\\V1\xe2\x02AGithub\\Com\\PechatnovVladimir\\MsaBigTech\\Social\\Api\\V1\\GPBMetadata\xea\x02;Github::Com::PechatnovVladimir::MsaBigTech::Social::Api::V1b\x06proto3"

var file_api_social_v1_service_proto_goTypes = []any{
	(*SendFriendRequestRequest)(nil),     // 0: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SendFriendRequestRequest
	(*ListRequestsRequest)(nil),          // 1: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListRequestsRequest
	(*AcceptFriendRequestRequest)(nil),   // 2: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.AcceptFriendRequestRequest
	(*DeclineFriendRequestRequest)(nil),  // 3: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.DeclineFriendRequestRequest
	(*RemoveFriendRequest)(nil),          // 4: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.RemoveFriendRequest
	(*ListFriendsRequest)(nil),           // 5: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListFriendsRequest
	(*SendFriendRequestResponse)(nil),    // 6: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SendFriendRequestResponse
	(*ListRequestsResponse)(nil),         // 7: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListRequestsResponse
	(*AcceptFriendRequestResponse)(nil),  // 8: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.AcceptFriendRequestResponse
	(*DeclineFriendRequestResponse)(nil), // 9: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.DeclineFriendRequestResponse
	(*RemoveFriendResponse)(nil),         // 10: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.RemoveFriendResponse
	(*ListFriendsResponse)(nil),          // 11: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListFriendsResponse
}
var file_api_social_v1_service_proto_depIdxs = []int32{
	0,  // 0: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.SendFriendRequest:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SendFriendRequestRequest
	1,  // 1: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.ListRequests:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListRequestsRequest
	2,  // 2: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.AcceptFriendRequest:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.AcceptFriendRequestRequest
	3,  // 3: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.DeclineFriendRequest:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.DeclineFriendRequestRequest
	4,  // 4: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.RemoveFriend:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.RemoveFriendRequest
	5,  // 5: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.ListFriends:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListFriendsRequest
	6,  // 6: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.SendFriendRequest:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SendFriendRequestResponse
	7,  // 7: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.ListRequests:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListRequestsResponse
	8,  // 8: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.AcceptFriendRequest:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.AcceptFriendRequestResponse
	9,  // 9: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.DeclineFriendRequest:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.DeclineFriendRequestResponse
	10, // 10: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.RemoveFriend:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.RemoveFriendResponse
	11, // 11: github.com.PechatnovVladimir.msa_big_tech.social.api.v1.SocialService.ListFriends:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.v1.ListFriendsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_social_v1_service_proto_init() }
func file_api_social_v1_service_proto_init() {
	if File_api_social_v1_service_proto != nil {
		return
	}
	file_api_social_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_social_v1_service_proto_rawDesc), len(file_api_social_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_social_v1_service_proto_goTypes,
		DependencyIndexes: file_api_social_v1_service_proto_depIdxs,
	}.Build()
	File_api_social_v1_service_proto = out.File
	file_api_social_v1_service_proto_goTypes = nil
	file_api_social_v1_service_proto_depIdxs = nil
}
