app:
  name:     USERS_SERVICE
  version:  v.0.0.1
  mode:     debug # debug | production
postgres:
  host:     localhost
  port:     5434
  database: postgres-users
  #user:     postgres-users-user_config
  #password: postgres-users-psw_config
  sslmode:  disable
grpc:
  server:
    host: localhost
    port: 50054
kafka_producer:
  brokers:
kafka_consumer:
  brokers:
