app:
  name:     USERS_SERVICE
  version:  v.0.0.1
  mode:     debug # debug | production
postgres:
  host:     postgresql-users
  port:     5432
  database: postgres-users
  user:     postgres-users-user
  password: postgres-users-psw
  sslmode:  disable
grpc:
  server:
    host: localhost
    port: 50054
    timeout:
      enabled: true
      ignore: [""] # black list
      timeoutMs: 5000 # дефолтный серверный таймаут
      paths:
        - path: "/api.users.v1.UsersService/CreateProfile"
          timeoutMs: 1000 # переопределенный таймаут для метода
    rateLimit:
      enabled: true
      ignore: [""] # black list
      reqPerSec: 1000 # дефолтный серверный ratelimit
      paths:
        - path: "/api.users.v1.UsersService/CreateProfile"
          reqPerSec: 10 # переопределенный ratelimit для метода
kafka_producer:
  brokers:
kafka_consumer:
  brokers:
