version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth-service
    ports:
      - "50051:50051"
    networks:
      - msa-network
    restart: unless-stopped
    environment:
      - GRPC_PORT=50051
    # volumes:
    #   - ./auth/configs:/root/configs:ro

  chat-service:
    build:
      context: .
      dockerfile: chat/Dockerfile
    container_name: chat-service
    ports:
      - "50052:50052"
    networks:
      - msa-network
    restart: unless-stopped
    environment:
      - GRPC_PORT=50052
      - AUTH_SERVICE_ADDRESS=auth-service:50051
    depends_on:
      - auth-service
    # volumes:
    #   - ./chat/configs:/root/configs:ro

networks:
  msa-network:
    driver: bridge