// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: api/social.proto

package social

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN  Status = 0
	Status_PENDING  Status = 1
	Status_ACCEPTED Status = 2
	Status_DECLINED Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "ACCEPTED",
		3: "DECLINED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":  0,
		"PENDING":  1,
		"ACCEPTED": 2,
		"DECLINED": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_social_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_social_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{0}
}

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=github.com.PechatnovVladimir.msa_big_tech.social.api.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_api_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FriendRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_api_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendRequestRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SendFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendRequest *FriendRequest         `protobuf:"bytes,1,opt,name=FriendRequest,proto3" json:"FriendRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_api_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{2}
}

func (x *SendFriendRequestResponse) GetFriendRequest() *FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

type ListRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_api_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequestsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendRequest []*FriendRequest       `protobuf:"bytes,1,rep,name=FriendRequest,proto3" json:"FriendRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_api_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequestsResponse) GetFriendRequest() []*FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

type AcceptFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestRequest) Reset() {
	*x = AcceptFriendRequestRequest{}
	mi := &file_api_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestRequest) ProtoMessage() {}

func (x *AcceptFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptFriendRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AcceptFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendRequest *FriendRequest         `protobuf:"bytes,1,opt,name=FriendRequest,proto3" json:"FriendRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestResponse) Reset() {
	*x = AcceptFriendRequestResponse{}
	mi := &file_api_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestResponse) ProtoMessage() {}

func (x *AcceptFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptFriendRequestResponse) GetFriendRequest() *FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

type DeclineFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequestRequest) Reset() {
	*x = DeclineFriendRequestRequest{}
	mi := &file_api_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequestRequest) ProtoMessage() {}

func (x *DeclineFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{7}
}

func (x *DeclineFriendRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type DeclineFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendRequest *FriendRequest         `protobuf:"bytes,1,opt,name=FriendRequest,proto3" json:"FriendRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequestResponse) Reset() {
	*x = DeclineFriendRequestResponse{}
	mi := &file_api_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequestResponse) ProtoMessage() {}

func (x *DeclineFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{8}
}

func (x *DeclineFriendRequestResponse) GetFriendRequest() *FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

type RemoveFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendRequest) Reset() {
	*x = RemoveFriendRequest{}
	mi := &file_api_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRequest) ProtoMessage() {}

func (x *RemoveFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRequest.ProtoReflect.Descriptor instead.
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveFriendRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResponse) Reset() {
	*x = RemoveFriendResponse{}
	mi := &file_api_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResponse) ProtoMessage() {}

func (x *RemoveFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResponse.ProtoReflect.Descriptor instead.
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{10}
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_api_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{11}
}

func (x *Cursor) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Cursor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_api_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{12}
}

func (x *ListFriendsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFriendsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFriendsRequest) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type ListFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendUserIds []int64                `protobuf:"varint,1,rep,packed,name=friend_user_ids,json=friendUserIds,proto3" json:"friend_user_ids,omitempty"`
	NextCursor    *Cursor                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_api_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_api_social_proto_rawDescGZIP(), []int{13}
}

func (x *ListFriendsResponse) GetFriendUserIds() []int64 {
	if x != nil {
		return x.FriendUserIds
	}
	return nil
}

func (x *ListFriendsResponse) GetNextCursor() *Cursor {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

var File_api_social_proto protoreflect.FileDescriptor

const file_api_social_proto_rawDesc = "" +
	"\n" +
	"\x10api/social.proto\x124github.com.PechatnovVladimir.msa_big_tech.social.api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cgoogle/api/annotations.proto\"\x84\x01\n" +
	"\rFriendRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12T\n" +
	"\x06status\x18\x02 \x01(\x0e2<.github.com.PechatnovVladimir.msa_big_tech.social.api.StatusR\x06status\"3\n" +
	"\x18SendFriendRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x86\x01\n" +
	"\x19SendFriendRequestResponse\x12i\n" +
	"\rFriendRequest\x18\x01 \x01(\v2C.github.com.PechatnovVladimir.msa_big_tech.social.api.FriendRequestR\rFriendRequest\".\n" +
	"\x13ListRequestsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x81\x01\n" +
	"\x14ListRequestsResponse\x12i\n" +
	"\rFriendRequest\x18\x01 \x03(\v2C.github.com.PechatnovVladimir.msa_big_tech.social.api.FriendRequestR\rFriendRequest\";\n" +
	"\x1aAcceptFriendRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\"\x88\x01\n" +
	"\x1bAcceptFriendRequestResponse\x12i\n" +
	"\rFriendRequest\x18\x01 \x01(\v2C.github.com.PechatnovVladimir.msa_big_tech.social.api.FriendRequestR\rFriendRequest\"<\n" +
	"\x1bDeclineFriendRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\"\x89\x01\n" +
	"\x1cDeclineFriendRequestResponse\x12i\n" +
	"\rFriendRequest\x18\x01 \x01(\v2C.github.com.PechatnovVladimir.msa_big_tech.social.api.FriendRequestR\rFriendRequest\".\n" +
	"\x13RemoveFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x16\n" +
	"\x14RemoveFriendResponse\"\\\n" +
	"\x06Cursor\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa9\x01\n" +
	"\x12ListFriendsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12Y\n" +
	"\x06cursor\x18\x03 \x01(\v2<.github.com.PechatnovVladimir.msa_big_tech.social.api.CursorH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\xb1\x01\n" +
	"\x13ListFriendsResponse\x12&\n" +
	"\x0ffriend_user_ids\x18\x01 \x03(\x03R\rfriendUserIds\x12b\n" +
	"\vnext_cursor\x18\x02 \x01(\v2<.github.com.PechatnovVladimir.msa_big_tech.social.api.CursorH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor*>\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bACCEPTED\x10\x02\x12\f\n" +
	"\bDECLINED\x10\x032\xb8\n" +
	"\n" +
	"\rSocialService\x12\xdd\x01\n" +
	"\x11SendFriendRequest\x12N.github.com.PechatnovVladimir.msa_big_tech.social.api.SendFriendRequestRequest\x1aO.github.com.PechatnovVladimir.msa_big_tech.social.api.SendFriendRequestResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/social/SendFriendRequest\x12\xd0\x01\n" +
	"\fListRequests\x12I.github.com.PechatnovVladimir.msa_big_tech.social.api.ListRequestsRequest\x1aJ.github.com.PechatnovVladimir.msa_big_tech.social.api.ListRequestsResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/social/ListRequests/{user_id}\x12\xe5\x01\n" +
	"\x13AcceptFriendRequest\x12P.github.com.PechatnovVladimir.msa_big_tech.social.api.AcceptFriendRequestRequest\x1aQ.github.com.PechatnovVladimir.msa_big_tech.social.api.AcceptFriendRequestResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/social/AcceptFriendRequest\x12\xe9\x01\n" +
	"\x14DeclineFriendRequest\x12Q.github.com.PechatnovVladimir.msa_big_tech.social.api.DeclineFriendRequestRequest\x1aR.github.com.PechatnovVladimir.msa_big_tech.social.api.DeclineFriendRequestResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/social/DeclineFriendRequest\x12\xd0\x01\n" +
	"\fRemoveFriend\x12I.github.com.PechatnovVladimir.msa_big_tech.social.api.RemoveFriendRequest\x1aJ.github.com.PechatnovVladimir.msa_big_tech.social.api.RemoveFriendResponse\")\x82\xd3\xe4\x93\x02#*!/v1/social/RemoveFriend/{user_id}\x12\xcc\x01\n" +
	"\vListFriends\x12H.github.com.PechatnovVladimir.msa_big_tech.social.api.ListFriendsRequest\x1aI.github.com.PechatnovVladimir.msa_big_tech.social.api.ListFriendsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/social/ListFriends/{user_id}Bj\x92A*\x12%\n" +
	"\n" +
	"Social API\x12\x12API social-service2\x031.0*\x01\x01Z;github.com/PechatnovVladimir/msa_big_tech/social/pkg;socialb\x06proto3"

var (
	file_api_social_proto_rawDescOnce sync.Once
	file_api_social_proto_rawDescData []byte
)

func file_api_social_proto_rawDescGZIP() []byte {
	file_api_social_proto_rawDescOnce.Do(func() {
		file_api_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_social_proto_rawDesc), len(file_api_social_proto_rawDesc)))
	})
	return file_api_social_proto_rawDescData
}

var file_api_social_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_social_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_social_proto_goTypes = []any{
	(Status)(0),                          // 0: github.com.PechatnovVladimir.msa_big_tech.social.api.Status
	(*FriendRequest)(nil),                // 1: github.com.PechatnovVladimir.msa_big_tech.social.api.FriendRequest
	(*SendFriendRequestRequest)(nil),     // 2: github.com.PechatnovVladimir.msa_big_tech.social.api.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),    // 3: github.com.PechatnovVladimir.msa_big_tech.social.api.SendFriendRequestResponse
	(*ListRequestsRequest)(nil),          // 4: github.com.PechatnovVladimir.msa_big_tech.social.api.ListRequestsRequest
	(*ListRequestsResponse)(nil),         // 5: github.com.PechatnovVladimir.msa_big_tech.social.api.ListRequestsResponse
	(*AcceptFriendRequestRequest)(nil),   // 6: github.com.PechatnovVladimir.msa_big_tech.social.api.AcceptFriendRequestRequest
	(*AcceptFriendRequestResponse)(nil),  // 7: github.com.PechatnovVladimir.msa_big_tech.social.api.AcceptFriendRequestResponse
	(*DeclineFriendRequestRequest)(nil),  // 8: github.com.PechatnovVladimir.msa_big_tech.social.api.DeclineFriendRequestRequest
	(*DeclineFriendRequestResponse)(nil), // 9: github.com.PechatnovVladimir.msa_big_tech.social.api.DeclineFriendRequestResponse
	(*RemoveFriendRequest)(nil),          // 10: github.com.PechatnovVladimir.msa_big_tech.social.api.RemoveFriendRequest
	(*RemoveFriendResponse)(nil),         // 11: github.com.PechatnovVladimir.msa_big_tech.social.api.RemoveFriendResponse
	(*Cursor)(nil),                       // 12: github.com.PechatnovVladimir.msa_big_tech.social.api.Cursor
	(*ListFriendsRequest)(nil),           // 13: github.com.PechatnovVladimir.msa_big_tech.social.api.ListFriendsRequest
	(*ListFriendsResponse)(nil),          // 14: github.com.PechatnovVladimir.msa_big_tech.social.api.ListFriendsResponse
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
}
var file_api_social_proto_depIdxs = []int32{
	0,  // 0: github.com.PechatnovVladimir.msa_big_tech.social.api.FriendRequest.status:type_name -> github.com.PechatnovVladimir.msa_big_tech.social.api.Status
	1,  // 1: github.com.PechatnovVladimir.msa_big_tech.social.api.SendFriendRequestResponse.FriendRequest:type_name -> github.com.PechatnovVladimir.msa_big_tech.social.api.FriendRequest
	1,  // 2: github.com.PechatnovVladimir.msa_big_tech.social.api.ListRequestsResponse.FriendRequest:type_name -> github.com.PechatnovVladimir.msa_big_tech.social.api.FriendRequest
	1,  // 3: github.com.PechatnovVladimir.msa_big_tech.social.api.AcceptFriendRequestResponse.FriendRequest:type_name -> github.com.PechatnovVladimir.msa_big_tech.social.api.FriendRequest
	1,  // 4: github.com.PechatnovVladimir.msa_big_tech.social.api.DeclineFriendRequestResponse.FriendRequest:type_name -> github.com.PechatnovVladimir.msa_big_tech.social.api.FriendRequest
	15, // 5: github.com.PechatnovVladimir.msa_big_tech.social.api.Cursor.created_at:type_name -> google.protobuf.Timestamp
	12, // 6: github.com.PechatnovVladimir.msa_big_tech.social.api.ListFriendsRequest.cursor:type_name -> github.com.PechatnovVladimir.msa_big_tech.social.api.Cursor
	12, // 7: github.com.PechatnovVladimir.msa_big_tech.social.api.ListFriendsResponse.next_cursor:type_name -> github.com.PechatnovVladimir.msa_big_tech.social.api.Cursor
	2,  // 8: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.SendFriendRequest:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.SendFriendRequestRequest
	4,  // 9: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.ListRequests:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.ListRequestsRequest
	6,  // 10: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.AcceptFriendRequest:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.AcceptFriendRequestRequest
	8,  // 11: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.DeclineFriendRequest:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.DeclineFriendRequestRequest
	10, // 12: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.RemoveFriend:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.RemoveFriendRequest
	13, // 13: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.ListFriends:input_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.ListFriendsRequest
	3,  // 14: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.SendFriendRequest:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.SendFriendRequestResponse
	5,  // 15: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.ListRequests:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.ListRequestsResponse
	7,  // 16: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.AcceptFriendRequest:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.AcceptFriendRequestResponse
	9,  // 17: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.DeclineFriendRequest:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.DeclineFriendRequestResponse
	11, // 18: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.RemoveFriend:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.RemoveFriendResponse
	14, // 19: github.com.PechatnovVladimir.msa_big_tech.social.api.SocialService.ListFriends:output_type -> github.com.PechatnovVladimir.msa_big_tech.social.api.ListFriendsResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_social_proto_init() }
func file_api_social_proto_init() {
	if File_api_social_proto != nil {
		return
	}
	file_api_social_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_social_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_social_proto_rawDesc), len(file_api_social_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_social_proto_goTypes,
		DependencyIndexes: file_api_social_proto_depIdxs,
		EnumInfos:         file_api_social_proto_enumTypes,
		MessageInfos:      file_api_social_proto_msgTypes,
	}.Build()
	File_api_social_proto = out.File
	file_api_social_proto_goTypes = nil
	file_api_social_proto_depIdxs = nil
}
