syntax = "proto3";

package  github.com.PechatnovVladimir.msa_big_tech.users.api;

option go_package = "github.com/PechatnovVladimir/msa_big_tech/users/pkg;users";

import "google/api/annotations.proto";


message UserProfile {
  int64 user_id = 1;
  string nickname = 2;
  string bio = 3;
  string avatar_url = 4;
}

service UserService {
  //создать профиль пользователя
  rpc CreateProfile(CreateProfileRequest) returns (CreateProfileResponse) {
    option (google.api.http) = {
      post: "/users/v1/CreateProfile"
      body: "*"
    };
  }

  //обновить профиль пользователя
  rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse) {
    option (google.api.http) = {
      patch: "/users/v1/UpdateProfile"
      body: "*"
    };
  }

  //получить профиль по ID
  rpc GetProfileByID(GetProfileByIDRequest) returns (GetProfileByIDResponse) {
    option (google.api.http) = {
      get: "/users/v1/GetProfileByID/{user_id}"
    };
  }

  //поиск по нику
  rpc GetProfileByNickname(GetProfileByNicknameRequest) returns (GetProfileByNicknameResponse) {
    option (google.api.http) = {
      get: "/users/v1/GetProfileByNickname/{nickname}"
    };
  }

  //поиск пользователей
  rpc SearchByNickname(SearchByNicknameRequest) returns (SearchByNicknameResponse) {
    option (google.api.http) = {
      post: "/users/v1/GetProfileByNickname"
    };
  }
}

message CreateProfileRequest {
  int64 user_id = 1;
  string nickname = 2;
  optional string bio = 3;
  optional string avatar_url = 4;
}

message CreateProfileResponse {
  UserProfile UserProfile = 1;
}

message UpdateProfileRequest {
  int64 user_id = 1;
  optional string nickname = 2;
  optional string bio = 3;
  optional string avatar_url = 4;
}

message UpdateProfileResponse {
  UserProfile UserProfile = 1;
}

message GetProfileByIDRequest {
  int64 user_id = 1;
}

message GetProfileByIDResponse {
  UserProfile UserProfile = 1;
}

message GetProfileByNicknameRequest {
  string nickname = 1;
}

message GetProfileByNicknameResponse {
  UserProfile UserProfile = 1;
}

message SearchByNicknameRequest {
  string query = 1;
  int64 limit = 2;
}

message SearchByNicknameResponse{
  repeated UserProfile UserProfile = 1;
}