syntax = "proto3";

package  github.com.PechatnovVladimir.msa_big_tech.users.api;

option go_package = "github.com/PechatnovVladimir/msa_big_tech/users/pkg;users";

message UserProfile {
  int64 user_id = 1;
  string nickname = 2;
  string bio = 3;
  string avatar_url = 4;
}

service UserService {
  //создать профиль пользователя
  rpc CreateProfile(CreateProfileRequest) returns (CreateProfileResponse) {}

  //обновить профиль пользователя
  rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse) {}

  //получить профиль по ID
  rpc GetProfileByID(GetProfileByIDRequest) returns (GetProfileByIDResponse) {}

  //поиск по нику
  rpc GetProfileByNickname(GetProfileByNicknameRequest) returns (GetProfileByNicknameResponse) {}

  //поиск пользователей
  rpc SearchByNickname(SearchByNicknameRequest) returns (SearchByNicknameResponse) {}
}

message CreateProfileRequest {
  int64 user_id = 1;
  string nickname = 2;
  string bio = 3;
  string avatar_url = 4;
}

message CreateProfileResponse {
  UserProfile UserProfile = 1;
}

message UpdateProfileRequest {
  int64 user_id = 1;
  string nickname = 2;
  string bio = 3;
  string avatar_url = 4;
}

message UpdateProfileResponse {
  UserProfile UserProfile = 1;
}

message GetProfileByIDRequest {
  int64 user_id = 1;
}

message GetProfileByIDResponse {
  UserProfile UserProfile = 1;
}

message GetProfileByNicknameRequest {
  string nickname = 1;
}

message GetProfileByNicknameResponse {
  UserProfile UserProfile = 1;
}

message SearchByNicknameRequest {
  string query = 1;
  int64 limit = 2;
}

message SearchByNicknameResponse{
  repeated UserProfile UserProfile = 1;
}