syntax = "proto3";

package github.com.PechatnovVladimir.msa_big_tech.social.api.v1;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "github.com/PechatnovVladimir/msa_big_tech/social/pkg/api/social/v1;social";

enum Status {
  UNKNOWN = 0;
  PENDING = 1;
  ACCEPTED = 2;
  DECLINED = 3;
}

message FriendRequest {
  string request_id = 1;
  Status status = 2;
}

message SendFriendRequestRequest {
  string user_id = 1;
}

message SendFriendRequestResponse {
  FriendRequest FriendRequest = 1;
}

message ListRequestsRequest {
  string user_id = 1;
}

message ListRequestsResponse {
  repeated FriendRequest FriendRequest = 1;
}

message AcceptFriendRequestRequest {
  string request_id = 1;
}

message AcceptFriendRequestResponse {
  FriendRequest FriendRequest = 1;
}

message DeclineFriendRequestRequest {
  string request_id = 1;
}

message DeclineFriendRequestResponse {
  FriendRequest FriendRequest = 1;
}

message RemoveFriendRequest {
  string user_id = 1;
}

message RemoveFriendResponse {}

message Cursor {
  string user_id = 1;
  google.protobuf.Timestamp created_at = 2;
}

message ListFriendsRequest {
  string user_id = 1;
  uint64 limit = 2;
  optional Cursor cursor = 3;
}

message ListFriendsResponse {
  repeated string friend_user_ids = 1;
  optional Cursor next_cursor = 2;
}
