// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/chat/v1/messages.proto

package chat

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chat - информация о чате
type Chat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id - ID чата в формате UUID
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// created_at - время создания чата
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// user_ids - участники чата
	UserIds       []string `protobuf:"bytes,3,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Chat) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Chat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chat) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// Message - информация о сообщении
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_id - ID сообщения
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// text - текст сообщения
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// CreateDirectChatRequest - запрос CreateDirectChat
type CreateDirectChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// participant_id - ID пользователя-владельца чата
	ParticipantId string `protobuf:"bytes,1,opt,name=participant_id,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatRequest) Reset() {
	*x = CreateDirectChatRequest{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatRequest) ProtoMessage() {}

func (x *CreateDirectChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectChatRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDirectChatRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

// CreateDirectChatResponse - ответ CreateDirectChat
type CreateDirectChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id - ID чата
	ChatId        string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatResponse) Reset() {
	*x = CreateDirectChatResponse{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatResponse) ProtoMessage() {}

func (x *CreateDirectChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectChatResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDirectChatResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// GetChatRequest - запрос GetChat
type GetChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id - ID чата
	ChatId        string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// GetChatResponse - ответ GetChat
type GetChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat - информация о чате
	Chat          *Chat `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResponse) Reset() {
	*x = GetChatResponse{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResponse) ProtoMessage() {}

func (x *GetChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResponse.ProtoReflect.Descriptor instead.
func (*GetChatResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

// ListUserChatsRequest - запрос ListUserChats
type ListUserChatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id - ID пользователя
	UserId        string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsRequest) Reset() {
	*x = ListUserChatsRequest{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsRequest) ProtoMessage() {}

func (x *ListUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserChatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListUserChatsResponse - ответ ListUserChats
type ListUserChatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chats - список чатов
	Chats         []*Chat `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsResponse) Reset() {
	*x = ListUserChatsResponse{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsResponse) ProtoMessage() {}

func (x *ListUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

// ListChatMembersRequest - запрос ListChatMembers
type ListChatMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id - ID чата
	ChatId        string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMembersRequest) Reset() {
	*x = ListChatMembersRequest{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMembersRequest) ProtoMessage() {}

func (x *ListChatMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMembersRequest.ProtoReflect.Descriptor instead.
func (*ListChatMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ListChatMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// ListChatMembersResponse - ответ ListChatMembers
type ListChatMembersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_ids - список пользователей
	UserIds       []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMembersResponse) Reset() {
	*x = ListChatMembersResponse{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMembersResponse) ProtoMessage() {}

func (x *ListChatMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMembersResponse.ProtoReflect.Descriptor instead.
func (*ListChatMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ListChatMembersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// SendMessageRequest - запрос SendMessage
type SendMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id - ID чата
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	// text - текст отправляемого сообщения
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// SendMessageResponse - ответ SendMessage
type SendMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message - информация о сообщении
	Message       *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// Cursor - cursor для пагинации маркер начала следующей страницы
type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *Cursor) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Cursor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListMessagesRequest - запрос ListMessages
type ListMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id - ID чата
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	Limit  uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// cursor - cursor для пагинации
	Cursor        *Cursor `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *ListMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ListMessagesRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

// ListMessagesResponse - ответ ListMessages
type ListMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// messages - список сообщений
	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// next_cursor - курсов для пагинации
	NextCursor    *Cursor `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetNextCursor() *Cursor {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

// StreamMessagesRequest - запрос StreamMessages
type StreamMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id - ID чата
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	// since_unix_ms - время начала стрима
	SinceUnixMs   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since_unix_ms,json=sinceUnixMs,proto3,oneof" json:"since_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *StreamMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *StreamMessagesRequest) GetSinceUnixMs() *timestamppb.Timestamp {
	if x != nil {
		return x.SinceUnixMs
	}
	return nil
}

// StreamMessagesResponse - ответ StreamMessages
type StreamMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message - информация о сообщении
	Message       *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesResponse) Reset() {
	*x = StreamMessagesResponse{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesResponse) ProtoMessage() {}

func (x *StreamMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesResponse.ProtoReflect.Descriptor instead.
func (*StreamMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *StreamMessagesResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_api_chat_v1_messages_proto protoreflect.FileDescriptor

const file_api_chat_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/chat/v1/messages.proto\x125github.com.PechatnovVladimir.msa_big_tech.chat.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xc4\x02\n" +
	"\x04Chat\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\tR\auserIds:\xcc\x01\x92A\xc8\x01\n" +
	"n*\x04Chat2'Chat - информация о чатеJ3{\"chat_id\": \"CD0F7430-FDDA-4E27-8C95-001E18E9CF50\"}\xd2\x01\achat_id*V\n" +
	"$Find out more about ABitOfEverything\x12.https://github.com/grpc-ecosystem/grpc-gateway\"\xc1\x02\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text:\x82\x02\x92A\xfe\x01\n" +
	"\xa3\x01*\aMessage24Message - информация о сообщенииJN{\"message_id\": \"CD0F7430-FDDA-4E27-8C95-001E18E9CF50\", \"text\": \"text message\"}\xd2\x01\n" +
	"message_id\xd2\x01\x04text*V\n" +
	"$Find out more about ABitOfEverything\x12.https://github.com/grpc-ecosystem/grpc-gateway\"Q\n" +
	"\x17CreateDirectChatRequest\x126\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0eparticipant_id\"3\n" +
	"\x18CreateDirectChatResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\":\n" +
	"\x0eGetChatRequest\x12(\n" +
	"\achat_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\achat_id\"b\n" +
	"\x0fGetChatResponse\x12O\n" +
	"\x04chat\x18\x01 \x01(\v2;.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatR\x04chat\"@\n" +
	"\x14ListUserChatsRequest\x12(\n" +
	"\auser_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\auser_id\"j\n" +
	"\x15ListUserChatsResponse\x12Q\n" +
	"\x05chats\x18\x01 \x03(\v2;.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatR\x05chats\"B\n" +
	"\x16ListChatMembersRequest\x12(\n" +
	"\achat_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\achat_id\"4\n" +
	"\x17ListChatMembersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"R\n" +
	"\x12SendMessageRequest\x12(\n" +
	"\achat_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\achat_id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"o\n" +
	"\x13SendMessageResponse\x12X\n" +
	"\amessage\x18\x01 \x01(\v2>.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.MessageR\amessage\"b\n" +
	"\x06Cursor\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xcd\x01\n" +
	"\x13ListMessagesRequest\x12(\n" +
	"\achat_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\achat_id\x12%\n" +
	"\x05limit\x18\x02 \x01(\x04B\x0f\xe0A\x02\xbaH\t\xc8\x01\x012\x04\x18d(\x05R\x05limit\x12Z\n" +
	"\x06cursor\x18\x03 \x01(\v2=.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.CursorH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\xe7\x01\n" +
	"\x14ListMessagesResponse\x12Z\n" +
	"\bmessages\x18\x01 \x03(\v2>.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.MessageR\bmessages\x12c\n" +
	"\vnext_cursor\x18\x02 \x01(\v2=.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.CursorH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"\x98\x01\n" +
	"\x15StreamMessagesRequest\x12(\n" +
	"\achat_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\achat_id\x12C\n" +
	"\rsince_unix_ms\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vsinceUnixMs\x88\x01\x01B\x10\n" +
	"\x0e_since_unix_ms\"r\n" +
	"\x16StreamMessagesResponse\x12X\n" +
	"\amessage\x18\x01 \x01(\v2>.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.MessageR\amessageB\x84\x03\n" +
	"9com.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1B\rMessagesProtoP\x01ZCgithub.com/PechatnovVladimir/msa_big_tech/chat/pkg/api/chat/v1;chat\xa2\x02\x06GCPMCA\xaa\x023Github.Com.PechatnovVladimir.MsaBigTech.Chat.Api.V1\xca\x023Github\\Com\\PechatnovVladimir\\MsaBigTech\\Chat\\Api\\V1\xe2\x02?Github\\Com\\PechatnovVladimir\\MsaBigTech\\Chat\\Api\\V1\\GPBMetadata\xea\x029Github::Com::PechatnovVladimir::MsaBigTech::Chat::Api::V1b\x06proto3"

var (
	file_api_chat_v1_messages_proto_rawDescOnce sync.Once
	file_api_chat_v1_messages_proto_rawDescData []byte
)

func file_api_chat_v1_messages_proto_rawDescGZIP() []byte {
	file_api_chat_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_chat_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chat_v1_messages_proto_rawDesc), len(file_api_chat_v1_messages_proto_rawDesc)))
	})
	return file_api_chat_v1_messages_proto_rawDescData
}

var file_api_chat_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_chat_v1_messages_proto_goTypes = []any{
	(*Chat)(nil),                     // 0: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Chat
	(*Message)(nil),                  // 1: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Message
	(*CreateDirectChatRequest)(nil),  // 2: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.CreateDirectChatRequest
	(*CreateDirectChatResponse)(nil), // 3: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.CreateDirectChatResponse
	(*GetChatRequest)(nil),           // 4: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.GetChatRequest
	(*GetChatResponse)(nil),          // 5: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.GetChatResponse
	(*ListUserChatsRequest)(nil),     // 6: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListUserChatsRequest
	(*ListUserChatsResponse)(nil),    // 7: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListUserChatsResponse
	(*ListChatMembersRequest)(nil),   // 8: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListChatMembersRequest
	(*ListChatMembersResponse)(nil),  // 9: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListChatMembersResponse
	(*SendMessageRequest)(nil),       // 10: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.SendMessageRequest
	(*SendMessageResponse)(nil),      // 11: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.SendMessageResponse
	(*Cursor)(nil),                   // 12: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Cursor
	(*ListMessagesRequest)(nil),      // 13: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),     // 14: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesResponse
	(*StreamMessagesRequest)(nil),    // 15: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.StreamMessagesRequest
	(*StreamMessagesResponse)(nil),   // 16: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.StreamMessagesResponse
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
}
var file_api_chat_v1_messages_proto_depIdxs = []int32{
	17, // 0: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Chat.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.GetChatResponse.chat:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Chat
	0,  // 2: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListUserChatsResponse.chats:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Chat
	1,  // 3: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.SendMessageResponse.message:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Message
	17, // 4: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Cursor.created_at:type_name -> google.protobuf.Timestamp
	12, // 5: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesRequest.cursor:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Cursor
	1,  // 6: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesResponse.messages:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Message
	12, // 7: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesResponse.next_cursor:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Cursor
	17, // 8: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.StreamMessagesRequest.since_unix_ms:type_name -> google.protobuf.Timestamp
	1,  // 9: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.StreamMessagesResponse.message:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.Message
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_chat_v1_messages_proto_init() }
func file_api_chat_v1_messages_proto_init() {
	if File_api_chat_v1_messages_proto != nil {
		return
	}
	file_api_chat_v1_messages_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_chat_v1_messages_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_chat_v1_messages_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_messages_proto_rawDesc), len(file_api_chat_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_chat_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_chat_v1_messages_proto_msgTypes,
	}.Build()
	File_api_chat_v1_messages_proto = out.File
	file_api_chat_v1_messages_proto_goTypes = nil
	file_api_chat_v1_messages_proto_depIdxs = nil
}
