// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/chat/v1/service.proto

package chat

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_chat_v1_service_proto protoreflect.FileDescriptor

const file_api_chat_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/chat/v1/service.proto\x125github.com.PechatnovVladimir.msa_big_tech.chat.api.v1\x1a\x1aapi/chat/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xad\v\n" +
	"\vChatService\x12\xd9\x01\n" +
	"\x10CreateDirectChat\x12N.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.CreateDirectChatRequest\x1aO.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.CreateDirectChatResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/chat/CreateDirectChat\x12\xbc\x01\n" +
	"\aGetChat\x12E.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.GetChatRequest\x1aF.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.GetChatResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/chat/GetChat/{chat_id}\x12\xd4\x01\n" +
	"\rListUserChats\x12K.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListUserChatsRequest\x1aL.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListUserChatsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/chat/ListUserChats/{user_id}\x12\xdc\x01\n" +
	"\x0fListChatMembers\x12M.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListChatMembersRequest\x1aN.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListChatMembersResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/chat/ListChatMembers/{chat_id}\x12\xc5\x01\n" +
	"\vSendMessage\x12I.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.SendMessageRequest\x1aJ.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.SendMessageResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/chat/SendMessage\x12\xd0\x01\n" +
	"\fListMessages\x12J.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesRequest\x1aK.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/chat/ListMessages/{chat_id}\x12\xb1\x01\n" +
	"\x0eStreamMessages\x12L.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.StreamMessagesRequest\x1aM.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.StreamMessagesResponse\"\x000\x01B\xac\x03\x92A&\x12!\n" +
	"\bChat API\x12\x10API chat-service2\x031.0*\x01\x01\n" +
	"9com.github.com.PechatnovVladimir.msa_big_tech.chat.api.v1B\fServiceProtoP\x01ZCgithub.com/PechatnovVladimir/msa_big_tech/chat/pkg/api/chat/v1;chat\xa2\x02\x06GCPMCA\xaa\x023Github.Com.PechatnovVladimir.MsaBigTech.Chat.Api.V1\xca\x023Github\\Com\\PechatnovVladimir\\MsaBigTech\\Chat\\Api\\V1\xe2\x02?Github\\Com\\PechatnovVladimir\\MsaBigTech\\Chat\\Api\\V1\\GPBMetadata\xea\x029Github::Com::PechatnovVladimir::MsaBigTech::Chat::Api::V1b\x06proto3"

var file_api_chat_v1_service_proto_goTypes = []any{
	(*CreateDirectChatRequest)(nil),  // 0: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.CreateDirectChatRequest
	(*GetChatRequest)(nil),           // 1: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.GetChatRequest
	(*ListUserChatsRequest)(nil),     // 2: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListUserChatsRequest
	(*ListChatMembersRequest)(nil),   // 3: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListChatMembersRequest
	(*SendMessageRequest)(nil),       // 4: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.SendMessageRequest
	(*ListMessagesRequest)(nil),      // 5: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesRequest
	(*StreamMessagesRequest)(nil),    // 6: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.StreamMessagesRequest
	(*CreateDirectChatResponse)(nil), // 7: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.CreateDirectChatResponse
	(*GetChatResponse)(nil),          // 8: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.GetChatResponse
	(*ListUserChatsResponse)(nil),    // 9: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListUserChatsResponse
	(*ListChatMembersResponse)(nil),  // 10: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListChatMembersResponse
	(*SendMessageResponse)(nil),      // 11: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.SendMessageResponse
	(*ListMessagesResponse)(nil),     // 12: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesResponse
	(*StreamMessagesResponse)(nil),   // 13: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.StreamMessagesResponse
}
var file_api_chat_v1_service_proto_depIdxs = []int32{
	0,  // 0: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.CreateDirectChat:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.CreateDirectChatRequest
	1,  // 1: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.GetChat:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.GetChatRequest
	2,  // 2: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.ListUserChats:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListUserChatsRequest
	3,  // 3: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.ListChatMembers:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListChatMembersRequest
	4,  // 4: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.SendMessage:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.SendMessageRequest
	5,  // 5: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.ListMessages:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesRequest
	6,  // 6: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.StreamMessages:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.StreamMessagesRequest
	7,  // 7: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.CreateDirectChat:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.CreateDirectChatResponse
	8,  // 8: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.GetChat:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.GetChatResponse
	9,  // 9: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.ListUserChats:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListUserChatsResponse
	10, // 10: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.ListChatMembers:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListChatMembersResponse
	11, // 11: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.SendMessage:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.SendMessageResponse
	12, // 12: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.ListMessages:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ListMessagesResponse
	13, // 13: github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.ChatService.StreamMessages:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.v1.StreamMessagesResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_chat_v1_service_proto_init() }
func file_api_chat_v1_service_proto_init() {
	if File_api_chat_v1_service_proto != nil {
		return
	}
	file_api_chat_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_service_proto_rawDesc), len(file_api_chat_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_v1_service_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_service_proto_depIdxs,
	}.Build()
	File_api_chat_v1_service_proto = out.File
	file_api_chat_v1_service_proto_goTypes = nil
	file_api_chat_v1_service_proto_depIdxs = nil
}
