// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/auth/v1/service.proto

package auth

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/auth/v1/service.proto\x125github.com.PechatnovVladimir.msa_big_tech.auth.api.v1\x1a\x1aapi/auth/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xb1\x04\n" +
	"\vAuthService\x12\xb9\x01\n" +
	"\bRegister\x12F.github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RegisterRequest\x1aG.github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RegisterResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/Register\x12\xad\x01\n" +
	"\x05Login\x12C.github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.LoginRequest\x1aD.github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/Login\x12\xb5\x01\n" +
	"\aRefresh\x12E.github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RefreshRequest\x1aF.github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RefreshResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/RefreshB\xac\x03\x92A&\x12!\n" +
	"\bAuth API\x12\x10API auth-service2\x031.0*\x01\x01\n" +
	"9com.github.com.PechatnovVladimir.msa_big_tech.auth.api.v1B\fServiceProtoP\x01ZCgithub.com/PechatnovVladimir/msa_big_tech/auth/pkg/api/auth/v1;auth\xa2\x02\x06GCPMAA\xaa\x023Github.Com.PechatnovVladimir.MsaBigTech.Auth.Api.V1\xca\x023Github\\Com\\PechatnovVladimir\\MsaBigTech\\Auth\\Api\\V1\xe2\x02?Github\\Com\\PechatnovVladimir\\MsaBigTech\\Auth\\Api\\V1\\GPBMetadata\xea\x029Github::Com::PechatnovVladimir::MsaBigTech::Auth::Api::V1b\x06proto3"

var file_api_auth_v1_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RegisterRequest
	(*LoginRequest)(nil),     // 1: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.LoginRequest
	(*RefreshRequest)(nil),   // 2: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RefreshRequest
	(*RegisterResponse)(nil), // 3: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RegisterResponse
	(*LoginResponse)(nil),    // 4: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.LoginResponse
	(*RefreshResponse)(nil),  // 5: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RefreshResponse
}
var file_api_auth_v1_service_proto_depIdxs = []int32{
	0, // 0: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.AuthService.Register:input_type -> github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RegisterRequest
	1, // 1: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.AuthService.Login:input_type -> github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.LoginRequest
	2, // 2: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.AuthService.Refresh:input_type -> github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RefreshRequest
	3, // 3: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.AuthService.Register:output_type -> github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RegisterResponse
	4, // 4: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.AuthService.Login:output_type -> github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.LoginResponse
	5, // 5: github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.AuthService.Refresh:output_type -> github.com.PechatnovVladimir.msa_big_tech.auth.api.v1.RefreshResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_service_proto_init() }
func file_api_auth_v1_service_proto_init() {
	if File_api_auth_v1_service_proto != nil {
		return
	}
	file_api_auth_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_service_proto_rawDesc), len(file_api_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_service_proto = out.File
	file_api_auth_v1_service_proto_goTypes = nil
	file_api_auth_v1_service_proto_depIdxs = nil
}
