// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/users/v1/messages.proto

package users

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserProfile - профиль пользователя
type UserProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id уникальный идентификатор пользователя в формате UUID генерируется автоматически при создании профиля
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// nickname никнейм пользователя
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// bio биография пользователя
	Bio string `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	// avatar_url ссылка на аватарку пользователя
	AvatarUrl     string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_users_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// CreateProfileRequest - запрос CreateProfile
type CreateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id - ID пользователя
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userid,proto3" json:"user_id,omitempty"`
	// nickname - никнейм пользователя
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// nickname - никнейм пользователя
	// bio биография пользователя
	Bio *string `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	// avatar_url ссылка на аватарку пользователя
	AvatarUrl     *string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateProfileRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *CreateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// CreateProfileResponse - ответ CreateProfile
type CreateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserProfile - полный профайл пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=UserProfile,proto3" json:"UserProfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProfileResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// UpdateProfileRequest - запрос UpdateProfile
type UpdateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id - ID пользователя в формате UUID
	UserId        string  `protobuf:"bytes,1,opt,name=user_id,json=userid,proto3" json:"user_id,omitempty"`
	Nickname      *string `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Bio           *string `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	AvatarUrl     *string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarurl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// UpdateProfileResponse - UpdateProfile ответ
type UpdateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserProfile - профайл пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=UserProfile,proto3" json:"UserProfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// GetProfileByIDRequest - GetProfileByID запрос
type GetProfileByIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id - ID пользователя в формате UUID
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userid,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDRequest) Reset() {
	*x = GetProfileByIDRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDRequest) ProtoMessage() {}

func (x *GetProfileByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetProfileByIDResponse - GetProfileByID ответ
type GetProfileByIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserProfile - профиль пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=UserProfile,proto3" json:"UserProfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDResponse) Reset() {
	*x = GetProfileByIDResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDResponse) ProtoMessage() {}

func (x *GetProfileByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfileByIDResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

type GetProfileByNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByNicknameRequest) Reset() {
	*x = GetProfileByNicknameRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByNicknameRequest) ProtoMessage() {}

func (x *GetProfileByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByNicknameRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileByNicknameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type GetProfileByNicknameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProfile   *UserProfile           `protobuf:"bytes,1,opt,name=UserProfile,proto3" json:"UserProfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByNicknameResponse) Reset() {
	*x = GetProfileByNicknameResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByNicknameResponse) ProtoMessage() {}

func (x *GetProfileByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByNicknameResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileByNicknameResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

type SearchByNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByNicknameRequest) Reset() {
	*x = SearchByNicknameRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByNicknameRequest) ProtoMessage() {}

func (x *SearchByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByNicknameRequest.ProtoReflect.Descriptor instead.
func (*SearchByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *SearchByNicknameRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchByNicknameRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchByNicknameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProfile   []*UserProfile         `protobuf:"bytes,1,rep,name=UserProfile,proto3" json:"UserProfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByNicknameResponse) Reset() {
	*x = SearchByNicknameResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByNicknameResponse) ProtoMessage() {}

func (x *SearchByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByNicknameResponse.ProtoReflect.Descriptor instead.
func (*SearchByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *SearchByNicknameResponse) GetUserProfile() []*UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

var File_api_users_v1_messages_proto protoreflect.FileDescriptor

const file_api_users_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/users/v1/messages.proto\x126github.com.PechatnovVladimir.msa_big_tech.users.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa3\x03\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl:\xad\x02\x92A\xa9\x02\n" +
	"\xce\x01*\vUserProfile25UserProfile - профиль пользователяJ`{\"nickname\": \"pvv\", \"email\": \"my-mail@mail.ru\", \"bio\": \"biography pvv\", \"avatar_url\": \"pvv.jpg\"}\xd2\x01\auser_id\xd2\x01\bnickname\xd2\x01\x03bio\xd2\x01\n" +
	"avatar_url*V\n" +
	"$Find out more about ABitOfEverything\x12.https://github.com/grpc-ecosystem/grpc-gateway\"\x9c\x03\n" +
	"\x14CreateProfileRequest\x12'\n" +
	"\auser_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06userid\x12>\n" +
	"\bnickname\x18\x02 \x01(\tB\"\xe0A\x02\xbaH\x1c\xc8\x01\x01r\x17\x10\x03\x18\x142\x11^[a-z0-9_]{3,20}$R\bnickname\x12 \n" +
	"\x03bio\x18\x03 \x01(\tB\t\xe0A\x01\xbaH\x03\xc8\x01\x00H\x00R\x03bio\x88\x01\x01\x12-\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tB\t\xe0A\x01\xbaH\x03\xc8\x01\x00H\x01R\tavatarUrl\x88\x01\x01:\xb2\x01\x92A\xae\x01\n" +
	"T*\x14CreateProfileRequest21CreateProfileRequest - запрос CreateProfile\xd2\x01\bnickname*V\n" +
	"$Find out more about ABitOfEverything\x12.https://github.com/grpc-ecosystem/grpc-gatewayB\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_url\"~\n" +
	"\x15CreateProfileResponse\x12e\n" +
	"\vUserProfile\x18\x01 \x01(\v2C.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfileR\vUserProfile\"\xad\x03\n" +
	"\x14UpdateProfileRequest\x12'\n" +
	"\auser_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06userid\x12C\n" +
	"\bnickname\x18\x02 \x01(\tB\"\xe0A\x01\xbaH\x1c\xc8\x01\x00r\x17\x10\x03\x18\x142\x11^[a-z0-9_]{3,20}$H\x00R\bnickname\x88\x01\x01\x12 \n" +
	"\x03bio\x18\x03 \x01(\tB\t\xe0A\x01\xbaH\x03\xc8\x01\x00H\x01R\x03bio\x88\x01\x01\x12-\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tB\t\xe0A\x01\xbaH\x03\xc8\x01\x00H\x02R\tavatarurl\x88\x01\x01:\xb1\x01\x92A\xad\x01\n" +
	"S*\x14UpdateProfileRequest21UpdateProfileRequest - запрос UpdateProfile\xd2\x01\auser_id*V\n" +
	"$Find out more about ABitOfEverything\x12.https://github.com/grpc-ecosystem/grpc-gatewayB\v\n" +
	"\t_nicknameB\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_url\"~\n" +
	"\x15UpdateProfileResponse\x12e\n" +
	"\vUserProfile\x18\x01 \x01(\v2C.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfileR\vUserProfile\"\xf7\x01\n" +
	"\x15GetProfileByIDRequest\x12'\n" +
	"\auser_id\x18\x01 \x01(\tB\x0e\xe0A\x02\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06userid:\xb4\x01\x92A\xb0\x01\n" +
	"V*\x15GetProfileByIDRequest23GetProfileByIDRequest - запрос GetProfileByID\xd2\x01\auser_id*V\n" +
	"$Find out more about ABitOfEverything\x12.https://github.com/grpc-ecosystem/grpc-gateway\"\x7f\n" +
	"\x16GetProfileByIDResponse\x12e\n" +
	"\vUserProfile\x18\x01 \x01(\v2C.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfileR\vUserProfile\"9\n" +
	"\x1bGetProfileByNicknameRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\"\x85\x01\n" +
	"\x1cGetProfileByNicknameResponse\x12e\n" +
	"\vUserProfile\x18\x01 \x01(\v2C.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfileR\vUserProfile\"E\n" +
	"\x17SearchByNicknameRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"\x81\x01\n" +
	"\x18SearchByNicknameResponse\x12e\n" +
	"\vUserProfile\x18\x01 \x03(\v2C.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfileR\vUserProfileB\x8c\x03\n" +
	":com.github.com.PechatnovVladimir.msa_big_tech.users.api.v1B\rMessagesProtoP\x01ZFgithub.com/PechatnovVladimir/msa_big_tech/users/pkg/api/users/v1;users\xa2\x02\x06GCPMUA\xaa\x024Github.Com.PechatnovVladimir.MsaBigTech.Users.Api.V1\xca\x024Github\\Com\\PechatnovVladimir\\MsaBigTech\\Users\\Api\\V1\xe2\x02@Github\\Com\\PechatnovVladimir\\MsaBigTech\\Users\\Api\\V1\\GPBMetadata\xea\x02:Github::Com::PechatnovVladimir::MsaBigTech::Users::Api::V1b\x06proto3"

var (
	file_api_users_v1_messages_proto_rawDescOnce sync.Once
	file_api_users_v1_messages_proto_rawDescData []byte
)

func file_api_users_v1_messages_proto_rawDescGZIP() []byte {
	file_api_users_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_users_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_users_v1_messages_proto_rawDesc), len(file_api_users_v1_messages_proto_rawDesc)))
	})
	return file_api_users_v1_messages_proto_rawDescData
}

var file_api_users_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_users_v1_messages_proto_goTypes = []any{
	(*UserProfile)(nil),                  // 0: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfile
	(*CreateProfileRequest)(nil),         // 1: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),        // 2: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.CreateProfileResponse
	(*UpdateProfileRequest)(nil),         // 3: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),        // 4: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UpdateProfileResponse
	(*GetProfileByIDRequest)(nil),        // 5: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByIDRequest
	(*GetProfileByIDResponse)(nil),       // 6: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByIDResponse
	(*GetProfileByNicknameRequest)(nil),  // 7: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByNicknameRequest
	(*GetProfileByNicknameResponse)(nil), // 8: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByNicknameResponse
	(*SearchByNicknameRequest)(nil),      // 9: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.SearchByNicknameRequest
	(*SearchByNicknameResponse)(nil),     // 10: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.SearchByNicknameResponse
}
var file_api_users_v1_messages_proto_depIdxs = []int32{
	0, // 0: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.CreateProfileResponse.UserProfile:type_name -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfile
	0, // 1: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UpdateProfileResponse.UserProfile:type_name -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfile
	0, // 2: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByIDResponse.UserProfile:type_name -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfile
	0, // 3: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByNicknameResponse.UserProfile:type_name -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfile
	0, // 4: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.SearchByNicknameResponse.UserProfile:type_name -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserProfile
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_users_v1_messages_proto_init() }
func file_api_users_v1_messages_proto_init() {
	if File_api_users_v1_messages_proto != nil {
		return
	}
	file_api_users_v1_messages_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_users_v1_messages_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_v1_messages_proto_rawDesc), len(file_api_users_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_users_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_users_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_users_v1_messages_proto_msgTypes,
	}.Build()
	File_api_users_v1_messages_proto = out.File
	file_api_users_v1_messages_proto_goTypes = nil
	file_api_users_v1_messages_proto_depIdxs = nil
}
