// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/users/v1/service.proto

package users

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_users_v1_service_proto protoreflect.FileDescriptor

const file_api_users_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/users/v1/service.proto\x126github.com.PechatnovVladimir.msa_big_tech.users.api.v1\x1a\x1bapi/users/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xe4\b\n" +
	"\vUserService\x12\xd0\x01\n" +
	"\rCreateProfile\x12L.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.CreateProfileRequest\x1aM.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.CreateProfileResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/users/CreateProfile\x12\xd0\x01\n" +
	"\rUpdateProfile\x12L.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UpdateProfileRequest\x1aM.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UpdateProfileResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/v1/users/UpdateProfile\x12\xdb\x01\n" +
	"\x0eGetProfileByID\x12M.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByIDRequest\x1aN.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByIDResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/users/GetProfileByID/{user_id}\x12\xf4\x01\n" +
	"\x14GetProfileByNickname\x12S.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByNicknameRequest\x1aT.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByNicknameResponse\"1\x82\xd3\xe4\x93\x02+\x12)/v1/users/GetProfileByNickname/{nickname}\x12\xd9\x01\n" +
	"\x10SearchByNickname\x12O.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.SearchByNicknameRequest\x1aP.github.com.PechatnovVladimir.msa_big_tech.users.api.v1.SearchByNicknameResponse\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/v1/users/SearchByNicknameB\xb6\x03\x92A(\x12#\n" +
	"\tUsers API\x12\x11API users-service2\x031.0*\x01\x01\n" +
	":com.github.com.PechatnovVladimir.msa_big_tech.users.api.v1B\fServiceProtoP\x01ZFgithub.com/PechatnovVladimir/msa_big_tech/users/pkg/api/users/v1;users\xa2\x02\x06GCPMUA\xaa\x024Github.Com.PechatnovVladimir.MsaBigTech.Users.Api.V1\xca\x024Github\\Com\\PechatnovVladimir\\MsaBigTech\\Users\\Api\\V1\xe2\x02@Github\\Com\\PechatnovVladimir\\MsaBigTech\\Users\\Api\\V1\\GPBMetadata\xea\x02:Github::Com::PechatnovVladimir::MsaBigTech::Users::Api::V1b\x06proto3"

var file_api_users_v1_service_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),         // 0: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.CreateProfileRequest
	(*UpdateProfileRequest)(nil),         // 1: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UpdateProfileRequest
	(*GetProfileByIDRequest)(nil),        // 2: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByIDRequest
	(*GetProfileByNicknameRequest)(nil),  // 3: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByNicknameRequest
	(*SearchByNicknameRequest)(nil),      // 4: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.SearchByNicknameRequest
	(*CreateProfileResponse)(nil),        // 5: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.CreateProfileResponse
	(*UpdateProfileResponse)(nil),        // 6: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UpdateProfileResponse
	(*GetProfileByIDResponse)(nil),       // 7: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByIDResponse
	(*GetProfileByNicknameResponse)(nil), // 8: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByNicknameResponse
	(*SearchByNicknameResponse)(nil),     // 9: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.SearchByNicknameResponse
}
var file_api_users_v1_service_proto_depIdxs = []int32{
	0, // 0: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserService.CreateProfile:input_type -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.CreateProfileRequest
	1, // 1: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserService.UpdateProfile:input_type -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UpdateProfileRequest
	2, // 2: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserService.GetProfileByID:input_type -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByIDRequest
	3, // 3: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserService.GetProfileByNickname:input_type -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByNicknameRequest
	4, // 4: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserService.SearchByNickname:input_type -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.SearchByNicknameRequest
	5, // 5: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserService.CreateProfile:output_type -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.CreateProfileResponse
	6, // 6: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserService.UpdateProfile:output_type -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UpdateProfileResponse
	7, // 7: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserService.GetProfileByID:output_type -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByIDResponse
	8, // 8: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserService.GetProfileByNickname:output_type -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.GetProfileByNicknameResponse
	9, // 9: github.com.PechatnovVladimir.msa_big_tech.users.api.v1.UserService.SearchByNickname:output_type -> github.com.PechatnovVladimir.msa_big_tech.users.api.v1.SearchByNicknameResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_users_v1_service_proto_init() }
func file_api_users_v1_service_proto_init() {
	if File_api_users_v1_service_proto != nil {
		return
	}
	file_api_users_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_v1_service_proto_rawDesc), len(file_api_users_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_v1_service_proto_goTypes,
		DependencyIndexes: file_api_users_v1_service_proto_depIdxs,
	}.Build()
	File_api_users_v1_service_proto = out.File
	file_api_users_v1_service_proto_goTypes = nil
	file_api_users_v1_service_proto_depIdxs = nil
}
