// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: api/chat.proto

package chat

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_api_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Chat) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Chat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateDirectChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId int64                  `protobuf:"varint,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatRequest) Reset() {
	*x = CreateDirectChatRequest{}
	mi := &file_api_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatRequest) ProtoMessage() {}

func (x *CreateDirectChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectChatRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDirectChatRequest) GetParticipantId() int64 {
	if x != nil {
		return x.ParticipantId
	}
	return 0
}

type CreateDirectChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatResponse) Reset() {
	*x = CreateDirectChatResponse{}
	mi := &file_api_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatResponse) ProtoMessage() {}

func (x *CreateDirectChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectChatResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDirectChatResponse) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type GetChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_api_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type GetChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResponse) Reset() {
	*x = GetChatResponse{}
	mi := &file_api_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResponse) ProtoMessage() {}

func (x *GetChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResponse.ProtoReflect.Descriptor instead.
func (*GetChatResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type ListUserChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsRequest) Reset() {
	*x = ListUserChatsRequest{}
	mi := &file_api_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsRequest) ProtoMessage() {}

func (x *ListUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserChatsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListUserChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsResponse) Reset() {
	*x = ListUserChatsResponse{}
	mi := &file_api_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsResponse) ProtoMessage() {}

func (x *ListUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ListChatMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMembersRequest) Reset() {
	*x = ListChatMembersRequest{}
	mi := &file_api_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMembersRequest) ProtoMessage() {}

func (x *ListChatMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMembersRequest.ProtoReflect.Descriptor instead.
func (*ListChatMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ListChatMembersRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type ListChatMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMembersResponse) Reset() {
	*x = ListChatMembersResponse{}
	mi := &file_api_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMembersResponse) ProtoMessage() {}

func (x *ListChatMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMembersResponse.ProtoReflect.Descriptor instead.
func (*ListChatMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ListChatMembersResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{10}
}

func (x *SendMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{11}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_api_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{12}
}

func (x *Cursor) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Cursor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_api_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{13}
}

func (x *ListMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ListMessagesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextCursor    *Cursor                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_api_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{14}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetNextCursor() *Cursor {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

type StreamMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SinceUnixMs   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since_unix_ms,json=sinceUnixMs,proto3,oneof" json:"since_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_api_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{15}
}

func (x *StreamMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *StreamMessagesRequest) GetSinceUnixMs() *timestamppb.Timestamp {
	if x != nil {
		return x.SinceUnixMs
	}
	return nil
}

type StreamMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesResponse) Reset() {
	*x = StreamMessagesResponse{}
	mi := &file_api_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesResponse) ProtoMessage() {}

func (x *StreamMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesResponse.ProtoReflect.Descriptor instead.
func (*StreamMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{16}
}

func (x *StreamMessagesResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_api_chat_proto protoreflect.FileDescriptor

const file_api_chat_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/chat.proto\x122github.com.PechatnovVladimir.msa_big_tech.chat.api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"3\n" +
	"\x04Chat\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"<\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"@\n" +
	"\x17CreateDirectChatRequest\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\x03R\rparticipantId\"3\n" +
	"\x18CreateDirectChatResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\")\n" +
	"\x0eGetChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"_\n" +
	"\x0fGetChatResponse\x12L\n" +
	"\x04chat\x18\x01 \x01(\v28.github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatR\x04chat\"/\n" +
	"\x14ListUserChatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"g\n" +
	"\x15ListUserChatsResponse\x12N\n" +
	"\x05chats\x18\x01 \x03(\v28.github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatR\x05chats\"1\n" +
	"\x16ListChatMembersRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"4\n" +
	"\x17ListChatMembersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"A\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"l\n" +
	"\x13SendMessageResponse\x12U\n" +
	"\amessage\x18\x01 \x01(\v2;.github.com.PechatnovVladimir.msa_big_tech.chat.api.MessageR\amessage\"b\n" +
	"\x06Cursor\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x98\x01\n" +
	"\x13ListMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12R\n" +
	"\x06cursor\x18\x03 \x01(\v2:.github.com.PechatnovVladimir.msa_big_tech.chat.api.CursorR\x06cursor\"\xe1\x01\n" +
	"\x14ListMessagesResponse\x12W\n" +
	"\bmessages\x18\x01 \x03(\v2;.github.com.PechatnovVladimir.msa_big_tech.chat.api.MessageR\bmessages\x12`\n" +
	"\vnext_cursor\x18\x02 \x01(\v2:.github.com.PechatnovVladimir.msa_big_tech.chat.api.CursorH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"\x87\x01\n" +
	"\x15StreamMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12C\n" +
	"\rsince_unix_ms\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vsinceUnixMs\x88\x01\x01B\x10\n" +
	"\x0e_since_unix_ms\"o\n" +
	"\x16StreamMessagesResponse\x12U\n" +
	"\amessage\x18\x01 \x01(\v2;.github.com.PechatnovVladimir.msa_big_tech.chat.api.MessageR\amessage2\x83\v\n" +
	"\vChatService\x12\xd3\x01\n" +
	"\x10CreateDirectChat\x12K.github.com.PechatnovVladimir.msa_big_tech.chat.api.CreateDirectChatRequest\x1aL.github.com.PechatnovVladimir.msa_big_tech.chat.api.CreateDirectChatResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/chat/CreateDirectChat\x12\xb6\x01\n" +
	"\aGetChat\x12B.github.com.PechatnovVladimir.msa_big_tech.chat.api.GetChatRequest\x1aC.github.com.PechatnovVladimir.msa_big_tech.chat.api.GetChatResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/chat/GetChat/{chat_id}\x12\xce\x01\n" +
	"\rListUserChats\x12H.github.com.PechatnovVladimir.msa_big_tech.chat.api.ListUserChatsRequest\x1aI.github.com.PechatnovVladimir.msa_big_tech.chat.api.ListUserChatsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/chat/ListUserChats/{user_id}\x12\xd6\x01\n" +
	"\x0fListChatMembers\x12J.github.com.PechatnovVladimir.msa_big_tech.chat.api.ListChatMembersRequest\x1aK.github.com.PechatnovVladimir.msa_big_tech.chat.api.ListChatMembersResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/chat/ListChatMembers/{chat_id}\x12\xbf\x01\n" +
	"\vSendMessage\x12F.github.com.PechatnovVladimir.msa_big_tech.chat.api.SendMessageRequest\x1aG.github.com.PechatnovVladimir.msa_big_tech.chat.api.SendMessageResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/chat/SendMessage\x12\xca\x01\n" +
	"\fListMessages\x12G.github.com.PechatnovVladimir.msa_big_tech.chat.api.ListMessagesRequest\x1aH.github.com.PechatnovVladimir.msa_big_tech.chat.api.ListMessagesResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/chat/ListMessages/{chat_id}\x12\xab\x01\n" +
	"\x0eStreamMessages\x12I.github.com.PechatnovVladimir.msa_big_tech.chat.api.StreamMessagesRequest\x1aJ.github.com.PechatnovVladimir.msa_big_tech.chat.api.StreamMessagesResponse\"\x000\x01Bb\x92A&\x12!\n" +
	"\bChat API\x12\x10API chat-service2\x031.0*\x01\x01Z7github.com/PechatnovVladimir/msa_big_tech/chat/pkg;chatb\x06proto3"

var (
	file_api_chat_proto_rawDescOnce sync.Once
	file_api_chat_proto_rawDescData []byte
)

func file_api_chat_proto_rawDescGZIP() []byte {
	file_api_chat_proto_rawDescOnce.Do(func() {
		file_api_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chat_proto_rawDesc), len(file_api_chat_proto_rawDesc)))
	})
	return file_api_chat_proto_rawDescData
}

var file_api_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_chat_proto_goTypes = []any{
	(*Chat)(nil),                     // 0: github.com.PechatnovVladimir.msa_big_tech.chat.api.Chat
	(*Message)(nil),                  // 1: github.com.PechatnovVladimir.msa_big_tech.chat.api.Message
	(*CreateDirectChatRequest)(nil),  // 2: github.com.PechatnovVladimir.msa_big_tech.chat.api.CreateDirectChatRequest
	(*CreateDirectChatResponse)(nil), // 3: github.com.PechatnovVladimir.msa_big_tech.chat.api.CreateDirectChatResponse
	(*GetChatRequest)(nil),           // 4: github.com.PechatnovVladimir.msa_big_tech.chat.api.GetChatRequest
	(*GetChatResponse)(nil),          // 5: github.com.PechatnovVladimir.msa_big_tech.chat.api.GetChatResponse
	(*ListUserChatsRequest)(nil),     // 6: github.com.PechatnovVladimir.msa_big_tech.chat.api.ListUserChatsRequest
	(*ListUserChatsResponse)(nil),    // 7: github.com.PechatnovVladimir.msa_big_tech.chat.api.ListUserChatsResponse
	(*ListChatMembersRequest)(nil),   // 8: github.com.PechatnovVladimir.msa_big_tech.chat.api.ListChatMembersRequest
	(*ListChatMembersResponse)(nil),  // 9: github.com.PechatnovVladimir.msa_big_tech.chat.api.ListChatMembersResponse
	(*SendMessageRequest)(nil),       // 10: github.com.PechatnovVladimir.msa_big_tech.chat.api.SendMessageRequest
	(*SendMessageResponse)(nil),      // 11: github.com.PechatnovVladimir.msa_big_tech.chat.api.SendMessageResponse
	(*Cursor)(nil),                   // 12: github.com.PechatnovVladimir.msa_big_tech.chat.api.Cursor
	(*ListMessagesRequest)(nil),      // 13: github.com.PechatnovVladimir.msa_big_tech.chat.api.ListMessagesRequest
	(*ListMessagesResponse)(nil),     // 14: github.com.PechatnovVladimir.msa_big_tech.chat.api.ListMessagesResponse
	(*StreamMessagesRequest)(nil),    // 15: github.com.PechatnovVladimir.msa_big_tech.chat.api.StreamMessagesRequest
	(*StreamMessagesResponse)(nil),   // 16: github.com.PechatnovVladimir.msa_big_tech.chat.api.StreamMessagesResponse
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
}
var file_api_chat_proto_depIdxs = []int32{
	0,  // 0: github.com.PechatnovVladimir.msa_big_tech.chat.api.GetChatResponse.chat:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.Chat
	0,  // 1: github.com.PechatnovVladimir.msa_big_tech.chat.api.ListUserChatsResponse.chats:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.Chat
	1,  // 2: github.com.PechatnovVladimir.msa_big_tech.chat.api.SendMessageResponse.message:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.Message
	17, // 3: github.com.PechatnovVladimir.msa_big_tech.chat.api.Cursor.created_at:type_name -> google.protobuf.Timestamp
	12, // 4: github.com.PechatnovVladimir.msa_big_tech.chat.api.ListMessagesRequest.cursor:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.Cursor
	1,  // 5: github.com.PechatnovVladimir.msa_big_tech.chat.api.ListMessagesResponse.messages:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.Message
	12, // 6: github.com.PechatnovVladimir.msa_big_tech.chat.api.ListMessagesResponse.next_cursor:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.Cursor
	17, // 7: github.com.PechatnovVladimir.msa_big_tech.chat.api.StreamMessagesRequest.since_unix_ms:type_name -> google.protobuf.Timestamp
	1,  // 8: github.com.PechatnovVladimir.msa_big_tech.chat.api.StreamMessagesResponse.message:type_name -> github.com.PechatnovVladimir.msa_big_tech.chat.api.Message
	2,  // 9: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.CreateDirectChat:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.CreateDirectChatRequest
	4,  // 10: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.GetChat:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.GetChatRequest
	6,  // 11: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.ListUserChats:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.ListUserChatsRequest
	8,  // 12: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.ListChatMembers:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.ListChatMembersRequest
	10, // 13: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.SendMessage:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.SendMessageRequest
	13, // 14: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.ListMessages:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.ListMessagesRequest
	15, // 15: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.StreamMessages:input_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.StreamMessagesRequest
	3,  // 16: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.CreateDirectChat:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.CreateDirectChatResponse
	5,  // 17: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.GetChat:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.GetChatResponse
	7,  // 18: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.ListUserChats:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.ListUserChatsResponse
	9,  // 19: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.ListChatMembers:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.ListChatMembersResponse
	11, // 20: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.SendMessage:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.SendMessageResponse
	14, // 21: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.ListMessages:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.ListMessagesResponse
	16, // 22: github.com.PechatnovVladimir.msa_big_tech.chat.api.ChatService.StreamMessages:output_type -> github.com.PechatnovVladimir.msa_big_tech.chat.api.StreamMessagesResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_chat_proto_init() }
func file_api_chat_proto_init() {
	if File_api_chat_proto != nil {
		return
	}
	file_api_chat_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_chat_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_proto_rawDesc), len(file_api_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_proto_goTypes,
		DependencyIndexes: file_api_chat_proto_depIdxs,
		MessageInfos:      file_api_chat_proto_msgTypes,
	}.Build()
	File_api_chat_proto = out.File
	file_api_chat_proto_goTypes = nil
	file_api_chat_proto_depIdxs = nil
}
